apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: alancs7/gitopsfc
  newTag: ec89014bf7b1ba6231108c80ec92443db1e9220d
