apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: alancs7/gitopsfc
  newTag: b4a090ba75d1268b0b7be821a533d7f698687d19
