apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: alancs7/gitopsfc
  newTag: c986adb0e5ba4846b42b3eeee0e9ee2d4aadd0ef
